Milestone 10 - Integration Tests
sneeu-leeu/MedicalBlog pull request #7
Opened 2022-05-18 19:19 UTC by sneeu-leeu

## In this milestone we:
 
Implemented tests for the following actions:

- Installed capybara

- Login page:

--display form fields and login button
--display error when incorrect data entered
--correct path after submitting correct data

- User index page:

-- display all user names
-- display all user photos
-- display all user posts number
-- correct path after clicking on a user

- User show page:

-- display user photo
-- display user name
-- display user written posts number
-- display user bio
-- display user 3 first posts
-- display post details page
--display correct path when clicked on post page
-- display all posts page

- User post index page:

-- display user photo
-- display user name
-- display user written posts number
-- display post title
-- display correct path after click in one post
-- display post body
-- display comments
-- display comment number
-- display like number

- Post show page:
-- display post title
-- display post author
-- display post comments
-- display post likes
-- display post body
-- display comment user name
-- display each comment

Test passed succesfully

2022-05-18 21:00 UTC, Gambit142 requested changes
Hi @sneeu-leeu @Yerimah 👋, 

Good job so far!

## Highlights

- Installed the `capybara` gem 💯 
- Wrote some tests for the `users#index` page
- Wrote some tests for the `users#show` page
- Wrote some tests for the `posts#index` page
- Wrote some tests for the `posts#show` page
- Wrote tests for the login page 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-18 21:00 UTC, Gambit142 commented on spec/features/login_spec.rb
> +  end
- [x] This test should prove that your app redirects to the `root_path` when the user inputs the correct **email** and **password**. Kindly make your app redirect to the `root_path` when the user inputs the correct **email** and **password**.

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_index.html.erb_spec.rb
> +    end
- [x] Kindly ensure that your test asserts that the app redirects to the `users#show` page when a user is clicked. You can do this: `expect(page).to have_current_path(user_path(the user id))`

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_index.html.erb_spec.rb
> +                            email: 'lewishamilton@f1.com', password: 'mercedes')
- [x] Kindly remove all linters disabling comments. Linters help us write `clean` and `maintainable` code and ensure that we adopt best practices when writing code in a certain language. You can use `@user1` instead of `@user_1`. Kindly fix it. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_index.html.erb_spec.rb
> +      end
- [x] Kindly remove all linters disabling comments. Linters help us write `clean` and `maintainable` code and ensure that we adopt best practices when writing code in a certain language. You can rename the picture so that the length of that string is shortened. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_show.html.erb_spec.rb
> +    end
- [x] This test should assert that your app redirects a user to the user's post's index page when the _**See all posts**_ button is clicked. Kindly make your test assert that: 

`expect(page).to have_current_path(user_posts_path(@user1.id))`

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_show.html.erb_spec.rb
> +end
- [ ] For the `users#show` page, you are missing the following tests:

- Tests that assert you can see the user's bio.
- Tests that assert you can see the user's first 3 posts.
- Tests that redirect to the post's show page when you click on a user's post.

#### Kindly implement this change. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_show.html.erb_spec.rb
> +                           email: 'test@test.com', password: 'vibesuh45', confirmed_at: Time.now)
- [x] Kindly remove all linters disabling comments. Linters help us write `clean` and `maintainable` code and ensure that we adopt best practices when writing code in a certain language. Kindly fix it. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/user/user_show.html.erb_spec.rb
> +      end
- [x] Kindly remove all linters disabling comments. Linters help us write `clean` and `maintainable` code and ensure that we adopt best practices when writing code in a certain language. You can rename the picture so that the length of that string is shortened. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/post/post_index.html.erb_spec.rb
> +    end
- [x] Kindly remove all linters disabling comments. Linters help us write `clean` and `maintainable` code and ensure that we adopt best practices when writing code in a certain language. Kindly fix it. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/post/post_index.html.erb_spec.rb
> +end
- [x] Great work writing these tests, I know they can be a lot but it is good practice to test all. This prepares you for real-world scenarios where you will write a lot of tests. Kindly add a test that:

- asserts you can see a section for pagination if there are more posts than fit on the view.

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/post/post_show.html.erb_spec.rb
> +
- [x] Kindly remove all linters disabling comments. Linters help us write `clean` and `maintainable` code and ensure that we adopt best practices when writing code in a certain language. Kindly fix it. 👍

2022-05-18 21:00 UTC, Gambit142 commented on spec/views/post/post_show.html.erb_spec.rb
> +end
- [x] Great work writing these tests, I know they can be a lot but it is good practice to test all. This prepares you for real-world scenarios where you will write a lot of tests. Kindly add a test that:

- asserts you can see how many likes it has.

2022-05-19 10:05 UTC, sneeu-leeu commented on spec/views/user/user_show.html.erb_spec.rb
> +      end
Thanks for the great reviews, as you can see in the App/assets/img folder, the picture is named quite shortly, but when directed through a browser the suffix is added, we can not rename it short enough to fit, and thus it is the only exception we have left in the app. Please excuse it as we can not break it into 2 lines either. Good thing that was built into the tech for these situations.

2022-05-19 10:40 UTC, sneeu-leeu commented
To the next reviewer; 

Please excuse the linter disabled for line to long regarding the image, the suffix as added when the image is passed through the browser and can not be changed

2022-05-19 10:51 UTC, uwadonat approved these changes
Hi @Team, 

Thank you for implementing requests suggested by previous reviewer. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-19 10:55 UTC, merged

2022-05-19 11:26 UTC, Mihndim2020 reviewed
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi Team, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._